# services:
#   #no cloudflare
#   client:
#     build:
#       context: ./client
#       target: dev
#     command: npm run dev #-- --host 0.0.0.0 --port 5173
#     environment:
#       NODE_ENV: development
#       CHOKIDAR_USEPOLLING: "true"
#     ports:
#       - "3000:5173"
#     volumes:
#       - ./client:/app
#       - /app/node_modules

#   server:
#     command: npm run dev
#     environment:
#       NODE_ENV: development
#       PORT: "5000"
#       MONGO_URL: mongodb://db:27017/appdb
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./server:/app
#       - /app/node_modules

#   db:
#     # Standard Mongo port on the host for local tools like Mongo Compass
#     ports:
#       - "27017:27017"



services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
