services:
  server:
    build:
      context: ./server
      target: dev
    environment:
      NODE_ENV: development
      PORT: "5000"
      # In docker network, use the service name "db"
      MONGO_URI: ${MONGO_URI}
    command: sh -lc "test -d node_modules && echo deps-ok || npm install; npm run dev"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "5000:5000"

  db:
    # optional but useful for mongosh from your host
    ports:
      - "27019:27017" #I had to change the external port because the native os mongo was hogging it for compass
    networks:
      - db_net
      - edge

volumes:
  server_node_modules:
