services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    # use the token style to avoid file issues. 
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    networks:
      - edge
    depends_on:
      - client
      - server
      
  client:
    build:
      context: ./client
      target: prod
    container_name: client
    restart: unless-stopped
    environment:
      NODE_ENV: production
    expose:
      - "5173"
    networks:
      - edge
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: prod
    container_name: server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
    expose:
      - "5000"
    networks:
      - edge
      - db_net
    depends_on:
      - db

  db:
    image: mongo:8.0
    container_name: db
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - db_net

networks:
  edge:
    name: portfolio_edge
  db_net:
    name: portfolio_db_net
    internal: true

volumes:
  mongo_data:
    name: portfolio_mongo_data
