services:

  cloudflared:
    profiles: ["tunnel"] # stops cloudflare unless i give --profile tunnel in compose command

  client:
    build:
      context: ./client
      target: dev
    working_dir: /app
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    command: sh -lc "test -x node_modules/.bin/vite || npm ci --include=dev; npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
      target: dev
    environment:
      NODE_ENV: development
      PORT: "5000"
      # In docker network, use the service name "db"
      MONGO_URI: ${MONGO_URI}
      command: sh -lc "test -x node_modules/.bin/nodemon || npm ci; npm run dev"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "5000:5000"

  db:
    ports:
      - "127.0.0.1:27019:27017" #I had to change the external port because the native os mongo was hogging it for compass
    networks:
      - db_net
      - edge

volumes:
  server_node_modules:
  client_node_modules: